[package]
name = "hello-grpc"
version = "0.1.0"
authors = ["ryutah <ryuta0221@gmail.com>"]

[dependencies]
grpc = "~0.4"
protobuf = "~1.6"
futures = "~0.1"
futures-cpupool = "~0.1"
tls-api = "~0.1"
tls-api-native-tls = "~0.1"

[build-dependencies]
protoc-rust-grpc = "~0.4"
