// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_e64ddc06bc23bd39, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_e64ddc06bc23bd39, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MultiGreetRequest struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiGreetRequest) Reset()         { *m = MultiGreetRequest{} }
func (m *MultiGreetRequest) String() string { return proto.CompactTextString(m) }
func (*MultiGreetRequest) ProtoMessage()    {}
func (*MultiGreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_e64ddc06bc23bd39, []int{2}
}
func (m *MultiGreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiGreetRequest.Unmarshal(m, b)
}
func (m *MultiGreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiGreetRequest.Marshal(b, m, deterministic)
}
func (dst *MultiGreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiGreetRequest.Merge(dst, src)
}
func (m *MultiGreetRequest) XXX_Size() int {
	return xxx_messageInfo_MultiGreetRequest.Size(m)
}
func (m *MultiGreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiGreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiGreetRequest proto.InternalMessageInfo

func (m *MultiGreetRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MultiGreetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MultiGreetReply struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiGreetReply) Reset()         { *m = MultiGreetReply{} }
func (m *MultiGreetReply) String() string { return proto.CompactTextString(m) }
func (*MultiGreetReply) ProtoMessage()    {}
func (*MultiGreetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_e64ddc06bc23bd39, []int{3}
}
func (m *MultiGreetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiGreetReply.Unmarshal(m, b)
}
func (m *MultiGreetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiGreetReply.Marshal(b, m, deterministic)
}
func (dst *MultiGreetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiGreetReply.Merge(dst, src)
}
func (m *MultiGreetReply) XXX_Size() int {
	return xxx_messageInfo_MultiGreetReply.Size(m)
}
func (m *MultiGreetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiGreetReply.DiscardUnknown(m)
}

var xxx_messageInfo_MultiGreetReply proto.InternalMessageInfo

func (m *MultiGreetReply) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MultiGreetReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "HelloReply")
	proto.RegisterType((*MultiGreetRequest)(nil), "MultiGreetRequest")
	proto.RegisterType((*MultiGreetReply)(nil), "MultiGreetReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	GetMultiGreet(ctx context.Context, in *MultiGreetRequest, opts ...grpc.CallOption) (Greeter_GetMultiGreetClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetMultiGreet(ctx context.Context, in *MultiGreetRequest, opts ...grpc.CallOption) (Greeter_GetMultiGreetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/Greeter/GetMultiGreet", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterGetMultiGreetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_GetMultiGreetClient interface {
	Recv() (*MultiGreetReply, error)
	grpc.ClientStream
}

type greeterGetMultiGreetClient struct {
	grpc.ClientStream
}

func (x *greeterGetMultiGreetClient) Recv() (*MultiGreetReply, error) {
	m := new(MultiGreetReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	GetMultiGreet(*MultiGreetRequest, Greeter_GetMultiGreetServer) error
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetMultiGreet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MultiGreetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).GetMultiGreet(m, &greeterGetMultiGreetServer{stream})
}

type Greeter_GetMultiGreetServer interface {
	Send(*MultiGreetReply) error
	grpc.ServerStream
}

type greeterGetMultiGreetServer struct {
	grpc.ServerStream
}

func (x *greeterGetMultiGreetServer) Send(m *MultiGreetReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMultiGreet",
			Handler:       _Greeter_GetMultiGreet_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_helloworld_e64ddc06bc23bd39) }

var fileDescriptor_helloworld_e64ddc06bc23bd39 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x48, 0xcd, 0xc9,
	0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0xe2,
	0xf1, 0x00, 0x89, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25,
	0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0x6a, 0x5c, 0x5c, 0x50,
	0x35, 0x05, 0x39, 0x95, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0x30, 0x45,
	0x30, 0xae, 0x92, 0x2d, 0x97, 0xa0, 0x6f, 0x69, 0x4e, 0x49, 0xa6, 0x7b, 0x51, 0x6a, 0x6a, 0x09,
	0xcc, 0x40, 0x11, 0x2e, 0xd6, 0xe4, 0xfc, 0xd2, 0xbc, 0x12, 0xb0, 0x62, 0xd6, 0x20, 0x08, 0x07,
	0x6e, 0x0d, 0x13, 0x92, 0x35, 0x8e, 0x5c, 0xfc, 0xc8, 0xda, 0x41, 0x76, 0x89, 0x70, 0xb1, 0x66,
	0xe6, 0xa5, 0xa4, 0x56, 0xc0, 0x34, 0x83, 0x39, 0xc8, 0x2e, 0x60, 0x42, 0x71, 0x81, 0x51, 0x1e,
	0x17, 0x3b, 0x58, 0x77, 0x6a, 0x91, 0x90, 0x06, 0x17, 0x47, 0x70, 0x62, 0x25, 0xd8, 0xdd, 0x42,
	0xbc, 0x7a, 0xc8, 0x7e, 0x94, 0xe2, 0xd6, 0x43, 0x78, 0x47, 0x89, 0x41, 0xc8, 0x92, 0x8b, 0xd7,
	0x3d, 0xb5, 0x04, 0x61, 0xb5, 0x90, 0x90, 0x1e, 0x86, 0x37, 0xa4, 0x04, 0xf4, 0xd0, 0xdc, 0xa6,
	0xc4, 0x60, 0xc0, 0x98, 0xc4, 0x06, 0x0e, 0x44, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0x28, 0xd0, 0x94, 0x58, 0x01, 0x00, 0x00,
}
